# Generated by Django 4.1.2 on 2022-11-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_name', models.CharField(max_length=50)),
                ('Class_Teacher', models.CharField(max_length=10)),
                ('Class_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=50)),
                ('Class_Id', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('Address', models.CharField(max_length=10)),
                ('Guardian', models.CharField(max_length=10)),
                ('Guardian_Contact', models.CharField(max_length=10)),
            ],
        ),
    ]
