# Generated by Django 4.1.2 on 2022-11-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='Class_Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.teacher'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Class_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.class'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Results_date', models.DateField()),
                ('Class_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.class')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.students')),
                ('Subject_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.subject')),
                ('Teacher_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.teacher')),
            ],
        ),
    ]
